[package]
name = "srt-transport"
version = "0.2.1"
authors = ["Russell Greene <russellgreene8@gmail.com>"]
description = "SRT implementation in Rust"
license = "Apache-2.0"
documentation = "https://docs.rs/srt"
homepage = "https://github.com/russelltg/srt-rs"
repository = "https://github.com/russelltg/srt-rs"

[dependencies]
tokio-core = "0.1"
tokio-io = "0.1"
tokio-udp = "0.1"
tokio-codec = "0.1"
futures = "0.1"
bytes = "0.4"
futures-timer = "0.1"
log = "0.4"
env_logger = "0.5"
rand = "0.5"
url = "1"
clap = "2"
bitflags = "1"
serde = "1"
serde_json = "1"
serde_derive = "1"
failure = "0.1"
failure_derive = "0.1"

[lib]
name = "srt"
path = "src/lib.rs"

[[bin]]
name = "stransmit-rs"
path = "src/bin.rs"

